### ISSUE TITLE
docs: document MQTT messages for Playnite Web Plugin

### ISSUE THREAD

**Issue by cvele** [andrew-codes/playnite-web#335]
The Playnite Web Plugin utilizes MQTT for communication by publishing and subscribing to various topics. We need comprehensive documentation for these MQTT messages, with a particular focus on the topics that the plugin subscribes to. This documentation will help developers understand the communication patterns and facilitate troubleshooting and future development.

**Tasks:**

- List all MQTT topics that the Playnite Web Plugin subscribes to.
- Describe the purpose of each subscribed topic.
- Provide message structure for each topic, including expected payload format.
- Include examples of messages for each subscribed topic.
- Document any relevant QoS levels and their implications for message delivery.
- Outline the MQTT topics that the Playnite Web Plugin publishes to, including message structure and examples.
- Review existing code to ensure all MQTT messages are accounted for.
- Create a Markdown file in the repository (e.g., `docs/mqtt-messages.md`) to house this documentation.

**Expected Outcome:**

A comprehensive Markdown file documenting all MQTT topics the Playnite Web Plugin subscribes to and publishes, including their purposes, message structures, examples, and QoS levels.

**Comment by andrew-codes** [comment]
I wanted to let @cvele  know that with this last release, v9.0.0, there is a breaking change to MQTT topics. I intend to release this now, so you get the fix for #580 , but know that this issue is the next thing on my radar: documenting the message and their formats. I'll include @cvele  on the PR once it is ready in case you want to review the content. Thanks!
