### ISSUE TITLE
Platform image is undefined

### ISSUE THREAD

**Issue by bfalala** [andrew-codes/playnite-web#608]
Hi,

I noticed one small issue with the platform image:
![image](https://github.com/user-attachments/assets/35e9ed1c-66ba-4185-a00b-7d99188b4eba)

It is undefined for all my games:
`<img data-test="PlatformListItem" alt="PC (Windows)" src="/asset-by-id/undefined" class="css-wtpnzt">`

It used to work a few releases back. I didn't see anything relevant in the log file.

Thanks for your work!

**Comment by andrew-codes** [comment]
@bfalala , what version are you using for the Plugin and Playnite Web? Also, did this happen after an upgrade? If so, which version did you go from and to? My suspicion is that the database may be in a bad state. Fortunately, there is nothing special stored now, so dropping the database and re-syncing usually is the path forward; assuming this was caused from an upgrade.

**Comment by andrew-codes** [comment]
Please let me know what you find and if you still have an issue. Otherwise, we can close this. I'll leave it open for a little bit in case there is still a problem. Thanks!

**Comment by bfalala** [comment]
I just tried to start clean by dropping the database and then did a full re-sync, but the issue is still there.
I don't notice anything suspicious in the logs (debug enabled). Just the consequence of the undefined image:

```
2024/11/11 20:03:45	stderr	      at /opt/playnite-web-app/server.production.js:83:16646
2024/11/11 20:03:45	stderr	      at /opt/playnite-web-app/server.production.js:81:17212
2024/11/11 20:03:45	stderr	      at ALl (/opt/playnite-web-app/server.production.js:81:18949)
2024/11/11 20:03:45	stderr	      at Object.v [as query] (/opt/playnite-web-app/server.production.js:64:45878)
2024/11/11 20:03:45	stderr	      at Ma (/opt/playnite-web-app/server.production.js:66:666)
2024/11/11 20:03:45	stderr	  error: Error: No route matches URL "/asset-by-id/undefined"
2024/11/11 20:03:45	stderr	  data: 'Error: No route matches URL "/asset-by-id/undefined"',
2024/11/11 20:03:45	stderr	  internal: true,
2024/11/11 20:03:45	stderr	  statusText: 'Not Found',
2024/11/11 20:03:45	stderr	  status: 404,
2024/11/11 20:03:45	stderr	vI {
2024/11/11 20:03:45	stderr	}
2024/11/11 20:03:45	stderr	      at /opt/playnite-web-app/server.production.js:83:16646
2024/11/11 20:03:45	stderr	      at /opt/playnite-web-app/server.production.js:81:17212
2024/11/11 20:03:45	stderr	      at ALl (/opt/playnite-web-app/server.production.js:81:18949)
2024/11/11 20:03:45	stderr	      at Object.v [as query] (/opt/playnite-web-app/server.production.js:64:45878)
2024/11/11 20:03:45	stderr	      at Ma (/opt/playnite-web-app/server.production.js:66:666)
2024/11/11 20:03:45	stderr	  error: Error: No route matches URL "/asset-by-id/undefined"
2024/11/11 20:03:45	stderr	  data: 'Error: No route matches URL "/asset-by-id/undefined"',
2024/11/11 20:03:45	stderr	  internal: true,
2024/11/11 20:03:45	stderr	  statusText: 'Not Found',
2024/11/11 20:03:45	stderr	  status: 404,
2024/11/11 20:03:45	stderr	vI {
2024/11/11 20:03:45	stderr	    at /opt/playnite-web-app/server.production.js:83:16646
2024/11/11 20:03:45	stderr	    at /opt/playnite-web-app/server.production.js:81:17212
2024/11/11 20:03:45	stderr	    at ALl (/opt/playnite-web-app/server.production.js:81:18949)
2024/11/11 20:03:45	stderr	    at Object.v [as query] (/opt/playnite-web-app/server.production.js:64:45878)
2024/11/11 20:03:45	stderr	    at Ma (/opt/playnite-web-app/server.production.js:66:666)
2024/11/11 20:03:45	stderr	Error: No route matches URL "/asset-by-id/undefined"
```

**Comment by andrew-codes** [comment]
Thanks for trying that. This is likely a sync related issue.

What are the library sources you have in your library? You mentioned that this used to work. Do you know what release you were using when it worked versus now? You have games, release, platforms, and sources; otherwise, the platform icon would not say PC (Windows) as its alt text. Platform icons and game assets are stored as webp files on Playnite Web's application server. However, the undefined value shows that when looking up the asset ID by platform ID and icon, it cannot find any results. This information is stored in the `gameasset` collection.

Let's try to find what is going wrong by looking at what data is synchronized. Please report the following:

1. What are the library sources you have in your library? Additionally, what does `db.source.find()` show any missing sources? What is the data that query returns?
2. What data is returned when using this query: `db.gameasset.find({ relatedType: 'Platform' })`? This should return all game assets that are related to platforms. My guess is that it may return no results, which is incorrect.

**Comment by bfalala** [comment]
Hi,

I ran your queries:
1. [games.source.json](https://github.com/user-attachments/files/17792509/games.source.json)
2. As expected `db.gameasset.find({ relatedType: 'Platform' })`  returned no results but `db.gameasset.find({ relatedType: 'Release' })` returned all games assets

**Comment by andrew-codes** [comment]
Ok, I think I've tracked down what is happening. Playnite allows you to set icons, cover images, etc. via its Library manager. My guess is that there are no images set in Playnite; meaning no image asset is published. As to why it used to work, Playnite Web used to default to a platform image that shipped with Playnite Web and no longer does this correctly. I plan to correctly default to the images and allow the overriding of these icons via Playnite instead of relying only on them being set in Playnite.

Once this is done, I'll cut a release for you to verify. Thanks again!

**Comment by andrew-codes** [comment]
Also, please note that I do not have default icons for all platforms, so the ideal solution is to set the icon image in Playnite.

**Comment by andrew-codes** [comment]
This is broken again as of 10.0.0. I suspect the default platform icon images are misconfigured in express. My guess is that the mounted directory for static assets works when running locally, but the relative path created when the app is packaged is incorrect. Furthermore, the data set used for testing has platforms that contain images coming from Playnite and therefore are not using the default platform images. This may be a reason why it is not caught when verifying, etc.

To complete this, the following will need to be completed:

- [ ] Change the test data set such that none of its platforms have associated game assets. This will allow testing efforts to expose if the default platform images are broken or not.
- [ ] Remove the platform images from the asset-by-id test data directory. These will no longer be needed.
- [ ] Ensure `src/public/assets` is configured by Express for static assets to be served. The `src/public/assets` should serve as the root of the site; i.e. `src/public/assets/platforms` is served as `https://playnite.web/platforms`.

**Comment by andrew-codes** [comment]
@bfalala , can you confirm what the HTML looks like for each of your platform images, but with the latest version and synchronizing the database; much like you did when you originally posted the issue? What I thought was the issue, may be incorrect.

I'm curious to see if your platforms with missing images have a `src` of something like `platforms/sony-playstation-5.webp`, `asset-by-id/undefined` or `asset-by-id/{some GUID value}`.

Also, have you set the platform images in Playnite or are you relying on the default ones provided by Playnite Web? You can see what images are set for a platform in Playnite via the Library Manager.

**Comment by bfalala** [comment]
Indeed, I have set the platform images in playnite.
So now, the HTML looks like this:
```
<img data-test="PlatformListItem" alt="PC (Windows)" src="BASEURL/platforms/pc-windows.webp" class="css-wtpnzt">
```

**Comment by andrew-codes** [comment]
Thanks! I'm making traction and will hopefully have a fix soon.

**Comment by andrew-codes** [comment]
I believe PR #664  addresses the problem. I'll cut a release soon.
