### ISSUE TITLE
Transition from playing one game to another

### ISSUE THREAD

**Issue by andrew-codes** [andrew-codes/playnite-web#615]
Given I am already actively playing a game, I may want to switch and play a different game. One way to accomplish this is to stop the current game and then start the next game. However, in this case, it may be undesirable to trigger any external automation that could be hooked into the stop game MQTT message.

I want to be able to transition from playing a game into a new game without triggering a request to stop the current game.

## Implementation Notes

When starting a game from Playnite Web's UI, consider checking if a game is already running. If not, then start the game normally. However, if a game is already running, then publish a MQTT message to transition a game, which is distinctly different from starting a game. This new message type should include the previous running release's information and the next release's information. With this, the plugin can stop the previous game and start the next one.

Note, we do not want to publish a launching state for the next game until the previous game has stopped. This is to ensure there is only one running release at a time.

**Comment by Shayviri** [comment]
Hey, sorry to step in this way. I just have a suggestion to do here.

Maybe, you should consider making this optional. Some games like League of Legend or other MMO games have their own launcher. Playnite consider the game 'running' when those launchers are online, even if the games are not actually running. Sometimes, people start those launchers to enter the queue to connect or just to talk with friends on those launchers while playing another game. This make Playnite think that you are actually playing 2 games in the same time. If you implement this without the option to not do it, then it would be impossible to open those launchers and another game through playnite web.
You can maybe add an argument 'transition' in the payload where we can put True or False. If it is not specified in the payload then you can put a default value of True.

Additionally, you can make the 'playnite/{deviceId}/response/game/state' mqtt publisher to not only publish the last updated release but all the releases running. Currently, it only publishes the state of the last updated release. If I launch a game, 'playnite/{deviceId}/response/game/state' publish the info of this release. But If I launch another game without stopping the first one, 'playnite/{deviceId}/response/game/state' only publish the state of the new game launch. Having 'playnite/{deviceId}/response/game/state' publishing all the release running at each update would help in those particular cases.

If you do it this way, then we might have a problem with the transition in the case several games are currently running in the same time. What happens if I put 'transition': True in the payload if several games are running? This is something to think about. An easy fix would be to send a warning, and in this particular case, not do the transition even if the argument is True and start the new game without stopping any games. But any other solutions may be better.

Again sorry if I step in without invitation. I just wanted to give some ideas and suggestions. I don't know how feasible it is for you. You can just skip what I say, of course!
